all: fp1.o fp3.o fp4.o fp5.o fp7.o

fp1.o:
	gcc -o forkprob1 forkprob1.c
fp3.o:
	gcc -o forkprob3 forkprob3.c
fp4.o:
	gcc -o forkprob4 forkprob4.c
fp5.o:
	gcc -o forkprob5 forkprob5.c
fp7.o:
	gcc -o forkprob7 forkprob7.c
clean:
	rm forkprob1 forkprob3 forkprob4 forkprob5 forkprob7 
